### ISSUE TITLE
The site seems to be down

### ISSUE THREAD

**Issue by thecashewtrader** [cferdinandi/vanilla-js-list#6]
Title, I'm not sure where this is built from, else I could've tried to fix issues if any

**Comment by cferdinandi** [comment]
Yea, I pulled it off the web sometime last year. It hadn't been updated in some time and I didn't have the ability to keep maintaining it. sorry!

**Comment by thecashewtrader** [comment]
Understandable, tho it'd be better if there was say a notice on the README or similar.
